# Generated by Django 4.2.7 on 2026-04-06 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=10)),
                ('student_code', models.CharField(max_length=10, unique=True)),
                ('bilet_code', models.CharField(max_length=30)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('last_login', models.IntegerField(blank=True, null=True)),
                ('twofa_enabled', models.BooleanField(default=False)),
                ('twofa_method', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(db_index=True, max_length=10)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'indexes': [models.Index(fields=['student_code', 'created_at'], name='user_sessio_student_9228b7_idx'), models.Index(fields=['student_code', 'last_activity'], name='user_sessio_student_838478_idx'), models.Index(fields=['browser'], name='user_sessio_browser_1e0b1a_idx'), models.Index(fields=['os'], name='user_sessio_os_08d65a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('avatar', 'Аватар'), ('banner', 'Баннер')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='api.user')),
            ],
            options={
                'db_table': 'user_profile_media',
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(db_index=True, max_length=10)),
                ('user_id', models.IntegerField(db_index=True)),
                ('banned_by_id', models.IntegerField(blank=True, null=True)),
                ('ban_date', models.DateTimeField(auto_now_add=True)),
                ('ban_duration_seconds', models.IntegerField()),
                ('ban_reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_bans',
                'indexes': [models.Index(fields=['student_code', 'is_active'], name='user_bans_student_f747ec_idx'), models.Index(fields=['user_id', 'is_active'], name='user_bans_user_id_0ec7f3_idx'), models.Index(fields=['banned_by_id'], name='user_bans_banned__afb79c_idx'), models.Index(fields=['ban_date'], name='user_bans_ban_dat_1ac94b_idx'), models.Index(fields=['created_at'], name='user_bans_created_e0458c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TelegramBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, default=0)),
                ('telegram_username', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('binding_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_binding', to='api.user')),
            ],
            options={
                'db_table': 'telegram_bindings',
            },
        ),
        migrations.CreateModel(
            name='MediaOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(choices=[('thumbnail', 'Миниатюра 150x150'), ('small', 'Маленький 300x300'), ('medium', 'Средний 800x600'), ('large', 'Большой 1200x800')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_versions', to='api.userprofilemedia')),
            ],
            options={
                'db_table': 'media_optimizations',
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Примечания о назначении')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='api.user')),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointed_admins', to='api.user')),
            ],
            options={
                'db_table': 'administration',
            },
        ),
        migrations.AddIndex(
            model_name='userprofilemedia',
            index=models.Index(fields=['user', 'media_type', 'is_active'], name='user_profil_user_id_5002fb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilemedia',
            index=models.Index(fields=['created_at'], name='user_profil_created_f9bb79_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambinding',
            index=models.Index(fields=['user', 'is_active'], name='telegram_bi_user_id_3fad75_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambinding',
            index=models.Index(fields=['telegram_id'], name='telegram_bi_telegra_32cfca_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambinding',
            index=models.Index(fields=['binding_token'], name='telegram_bi_binding_c4ca0e_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambinding',
            index=models.Index(fields=['created_at'], name='telegram_bi_created_357ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaoptimization',
            index=models.Index(fields=['original_media', 'size_type'], name='media_optim_origina_9427f4_idx'),
        ),
        migrations.AddIndex(
            model_name='administration',
            index=models.Index(fields=['administrator', 'is_active'], name='administrat_adminis_b89289_idx'),
        ),
        migrations.AddIndex(
            model_name='administration',
            index=models.Index(fields=['appointed_by'], name='administrat_appoint_697abe_idx'),
        ),
        migrations.AddIndex(
            model_name='administration',
            index=models.Index(fields=['appointed_at'], name='administrat_appoint_6ee24d_idx'),
        ),
    ]
