# Generated by Django 4.2.30 on 2026-05-04 21:46

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('fullname', models.CharField(max_length=100)),
                ('faculty', models.CharField(max_length=255)),
                ('student_code', models.CharField(max_length=10, unique=True)),
                ('role', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('chairperson', 'Председатель'), ('moderator', 'Модератор')], default='student', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('twofa_enabled', models.BooleanField(default=False)),
                ('twofa_method', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('auth_sync_managed', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(db_index=True, max_length=10)),
                ('session_key', models.CharField(max_length=40, unique=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('browser', models.CharField(blank=True, max_length=100, null=True)),
                ('os', models.CharField(blank=True, max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'indexes': [models.Index(fields=['student_code', 'created_at'], name='user_sessio_student_9228b7_idx'), models.Index(fields=['student_code', 'last_activity'], name='user_sessio_student_838478_idx'), models.Index(fields=['browser'], name='user_sessio_browser_1e0b1a_idx'), models.Index(fields=['os'], name='user_sessio_os_08d65a_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfileMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('avatar', 'Аватар'), ('banner', 'Баннер')], max_length=10)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile_media',
            },
        ),
        migrations.CreateModel(
            name='UserBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(db_index=True, max_length=10)),
                ('ban_date', models.DateTimeField(auto_now_add=True)),
                ('ban_duration_seconds', models.IntegerField()),
                ('ban_reason', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(blank=True, db_column='banned_by_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_bans', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_bans',
            },
        ),
        migrations.CreateModel(
            name='TelegramBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, default=0)),
                ('telegram_username', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('binding_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_binding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'telegram_bindings',
            },
        ),
        migrations.CreateModel(
            name='SupportThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('request_type', models.CharField(choices=[('support', 'Поддержка'), ('bug', 'Ошибка'), ('feature', 'Предложение'), ('question', 'Вопрос')], db_index=True, default='support', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Открыто'), ('answered', 'Есть ответ'), ('closed', 'Закрыто')], db_index=True, default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('assigned_moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_threads', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'support_threads',
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('is_moderator_reply', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_messages', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.supportthread')),
            ],
            options={
                'db_table': 'support_messages',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_number', models.CharField(db_index=True, max_length=20)),
                ('week', models.IntegerField()),
                ('day', models.CharField(max_length=32)),
                ('time', models.CharField(max_length=32)),
                ('matter', models.CharField(blank=True, max_length=500)),
                ('teacher', models.CharField(blank=True, max_length=255)),
                ('frame', models.CharField(blank=True, max_length=255)),
                ('classroom', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'schedule_entries',
                'indexes': [models.Index(fields=['group_number', 'day', 'week'], name='schedule_en_group_n_c454d1_idx'), models.Index(fields=['created_at'], name='schedule_en_created_b27b42_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=255, unique=True)),
                ('date', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.BigIntegerField(db_index=True, default=0)),
                ('summary', models.TextField(blank=True)),
                ('tags', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('reading_time', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'news_items',
                'indexes': [models.Index(fields=['timestamp'], name='news_items_timesta_f7c832_idx'), models.Index(fields=['created_at'], name='news_items_created_86992e_idx')],
            },
        ),
        migrations.CreateModel(
            name='MediaOptimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_type', models.CharField(choices=[('thumbnail', 'Миниатюра 150x150'), ('small', 'Маленький 300x300'), ('medium', 'Средний 800x600'), ('large', 'Большой 1200x800')], max_length=20)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='optimized_versions', to='api.userprofilemedia')),
            ],
            options={
                'db_table': 'media_optimizations',
            },
        ),
        migrations.CreateModel(
            name='LiteratureItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('handle', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('faculty', models.CharField(blank=True, max_length=64)),
                ('category', models.CharField(blank=True, max_length=191)),
                ('authors', models.TextField(blank=True)),
                ('publishing_date', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True, max_length=1000)),
                ('download_size', models.CharField(blank=True, max_length=100)),
                ('download_link', models.URLField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'literature_items',
                'indexes': [models.Index(fields=['handle'], name='literature__handle_9e31d5_idx'), models.Index(fields=['faculty'], name='literature__faculty_bf0899_idx'), models.Index(fields=['category'], name='literature__categor_435278_idx'), models.Index(fields=['publishing_date'], name='literature__publish_4da96a_idx'), models.Index(fields=['created_at'], name='literature__created_8a2dba_idx')],
            },
        ),
        migrations.CreateModel(
            name='DevTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('student_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('role', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'dev_team_members',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='dev_team_me_is_acti_d02dc7_idx'), models.Index(fields=['student_code'], name='dev_team_me_student_8479b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='BackgroundJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(db_index=True, max_length=100)),
                ('job_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('available_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'background_jobs',
                'indexes': [models.Index(fields=['status', 'available_at'], name='background__status_d47efd_idx'), models.Index(fields=['job_type', 'status'], name='background__job_typ_0be1ba_idx'), models.Index(fields=['created_at'], name='background__created_f99170_idx')],
            },
        ),
        migrations.CreateModel(
            name='Administration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointed_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Примечания о назначении')),
                ('administrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to=settings.AUTH_USER_MODEL)),
                ('appointed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointed_admins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'administration',
            },
        ),
        migrations.CreateModel(
            name='ActivityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('user_unbanned', 'Пользователь разблокирован'), ('admin_removed', 'Снятие администратора'), ('twofa_enabled', '2FA включен'), ('twofa_disabled', '2FA отключен'), ('telegram_unlinked', 'Telegram отвязан')], db_index=True, max_length=40)),
                ('details', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_activity_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_events',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_successful_login', models.BooleanField(default=True)),
                ('notify_support_replies', models.BooleanField(default=True)),
                ('notify_security_events', models.BooleanField(default=True)),
                ('show_profile_in_community', models.BooleanField(default=True)),
                ('show_faculty', models.BooleanField(default=True)),
                ('allow_telegram_discovery', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_settings',
                'indexes': [models.Index(fields=['notify_successful_login'], name='user_settin_notify__8ef2a0_idx'), models.Index(fields=['notify_support_replies'], name='user_settin_notify__fb7529_idx'), models.Index(fields=['notify_security_events'], name='user_settin_notify__13cbb0_idx'), models.Index(fields=['show_profile_in_community'], name='user_settin_show_pr_3fe17c_idx'), models.Index(fields=['created_at'], name='user_settin_created_9329a3_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='userprofilemedia',
            index=models.Index(fields=['user', 'media_type', 'is_active'], name='user_profil_user_id_5002fb_idx'),
        ),
        migrations.AddIndex(
            model_name='userprofilemedia',
            index=models.Index(fields=['created_at'], name='user_profil_created_f9bb79_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['student_code', 'is_active'], name='user_bans_student_f747ec_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user', 'is_active'], name='user_bans_user_id_0ec7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['banned_by'], name='user_bans_banned__afb79c_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['ban_date'], name='user_bans_ban_dat_1ac94b_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['created_at'], name='user_bans_created_e0458c_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambinding',
            index=models.Index(fields=['user', 'is_active'], name='telegram_bi_user_id_3fad75_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambinding',
            index=models.Index(fields=['telegram_id'], name='telegram_bi_telegra_32cfca_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambinding',
            index=models.Index(fields=['binding_token'], name='telegram_bi_binding_c4ca0e_idx'),
        ),
        migrations.AddIndex(
            model_name='telegrambinding',
            index=models.Index(fields=['created_at'], name='telegram_bi_created_357ab6_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['status', 'last_message_at'], name='support_thr_status_d1d00c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['request_type', 'last_message_at'], name='support_thr_request_aa7495_idx'),
        ),
        migrations.AddIndex(
            model_name='supportthread',
            index=models.Index(fields=['created_by', 'last_message_at'], name='support_thr_created_8d5faf_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['thread', 'created_at'], name='support_mes_thread__9d142c_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['author', 'created_at'], name='support_mes_author__f290a6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediaoptimization',
            index=models.Index(fields=['original_media', 'size_type'], name='media_optim_origina_9427f4_idx'),
        ),
        migrations.AddIndex(
            model_name='administration',
            index=models.Index(fields=['administrator', 'is_active'], name='administrat_adminis_b89289_idx'),
        ),
        migrations.AddIndex(
            model_name='administration',
            index=models.Index(fields=['appointed_by'], name='administrat_appoint_697abe_idx'),
        ),
        migrations.AddIndex(
            model_name='administration',
            index=models.Index(fields=['appointed_at'], name='administrat_appoint_6ee24d_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['event_type', 'created_at'], name='activity_ev_event_t_a0a379_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['user', 'created_at'], name='activity_ev_user_id_8f5de0_idx'),
        ),
        migrations.AddIndex(
            model_name='activityevent',
            index=models.Index(fields=['actor', 'created_at'], name='activity_ev_actor_i_3b0510_idx'),
        ),
    ]
