# Generated by Codex on 2026-04-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bilet_code',
            field=models.CharField(max_length=128),
        ),
    ]
