# Generated by Django 4.2.30 on 2026-05-16 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_usernotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_user_id_94ad44_idx',
            old_name='user_notifi_user_id_9328f3_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_user_id_d909fd_idx',
            old_name='user_notifi_user_id_1efa6e_idx',
        ),
        migrations.RenameIndex(
            model_name='usernotification',
            new_name='user_notifi_notific_645560_idx',
            old_name='user_notifi_notific_8b0a10_idx',
        ),
    ]
