# Generated by Codex on 2026-04-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_bilet_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bilet_code',
            new_name='password',
        ),
    ]
