# Generated by Django 6.0.4 on 2026-04-18 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_backgroundjob'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__status_d47efd_idx',
            old_name='background__status_303699_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__job_typ_0be1ba_idx',
            old_name='background__job_typ_a3c01c_idx',
        ),
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__created_f99170_idx',
            old_name='background__created_6ff52e_idx',
        ),
    ]
