# Generated by Django 4.2.30 on 2026-05-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_backgroundjob_priority'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='backgroundjob',
            new_name='background__status_304870_idx',
            old_name='background__status_32fd8e_idx',
        ),
    ]
