# Generated by Django 4.2.30 on 2026-05-22 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_events'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='event',
            new_name='events_status_a8c13d_idx',
            old_name='events_status_e0b3fe_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_created_1c1e59_idx',
            old_name='events_created_4231f1_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_created_9e2206_idx',
            old_name='events_created_57e4ee_idx',
        ),
        migrations.RenameIndex(
            model_name='eventparticipation',
            new_name='event_parti_event_i_08cf2c_idx',
            old_name='event_partic_event_i_2efd3c_idx',
        ),
        migrations.RenameIndex(
            model_name='eventparticipation',
            new_name='event_parti_user_id_f255b9_idx',
            old_name='event_partic_user_id_ea6a33_idx',
        ),
    ]
