# Generated by Django 4.2.7 on 2026-03-18 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_user_created_at_alter_user_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemedia',
            name='created_at',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
