# Generated by Django 4.2.7 on 2026-03-29 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_user_last_login_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, default=0)),
                ('telegram_username', models.CharField(blank=True, max_length=32, null=True)),
                ('telegram_first_name', models.CharField(blank=True, max_length=64, null=True)),
                ('telegram_last_name', models.CharField(blank=True, max_length=64, null=True)),
                ('binding_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_binding', to='api.user')),
            ],
            options={
                'db_table': 'telegram_bindings',
                'indexes': [models.Index(fields=['user', 'is_active'], name='telegram_bi_user_id_3fad75_idx'), models.Index(fields=['telegram_id'], name='telegram_bi_telegra_32cfca_idx'), models.Index(fields=['binding_token'], name='telegram_bi_binding_c4ca0e_idx'), models.Index(fields=['created_at'], name='telegram_bi_created_357ab6_idx')],
            },
        ),
    ]
