# Generated by Django 4.2.7 on 2026-04-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_newsitem_link'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='literatureitem',
            new_name='literature__faculty_bf0899_idx',
            old_name='literature__faculty_746d57_idx',
        ),
        migrations.RenameIndex(
            model_name='literatureitem',
            new_name='literature__categor_435278_idx',
            old_name='literature__categor_95f493_idx',
        ),
        migrations.RenameIndex(
            model_name='literatureitem',
            new_name='literature__publish_4da96a_idx',
            old_name='literature__publish_28f064_idx',
        ),
        migrations.RenameIndex(
            model_name='literatureitem',
            new_name='literature__created_8a2dba_idx',
            old_name='literature__created_a4eeff_idx',
        ),
        migrations.RenameIndex(
            model_name='newsitem',
            new_name='news_items_timesta_f7c832_idx',
            old_name='news_items_timestamp_5fd7c8_idx',
        ),
        migrations.RenameIndex(
            model_name='newsitem',
            new_name='news_items_created_86992e_idx',
            old_name='news_items_created_0f3a96_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleentry',
            new_name='schedule_en_group_n_c454d1_idx',
            old_name='schedule_en_group_n_7e69c8_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduleentry',
            new_name='schedule_en_created_b27b42_idx',
            old_name='schedule_en_created_beb901_idx',
        ),
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='user_settin_notify__8ef2a0_idx',
            old_name='user_settin_notify__74a3d9_idx',
        ),
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='user_settin_created_9329a3_idx',
            old_name='user_settin_created_4ea7fd_idx',
        ),
    ]
