# Generated by Django 4.2.30 on 2026-05-03 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_devteammember'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_event_t_a0a379_idx',
            old_name='activity_ev_event_t_7e6fd0_idx',
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_user_id_8f5de0_idx',
            old_name='activity_ev_user_id_0d4e0d_idx',
        ),
        migrations.RenameIndex(
            model_name='activityevent',
            new_name='activity_ev_actor_i_3b0510_idx',
            old_name='activity_ev_actor_id_132eaf_idx',
        ),
        migrations.RenameIndex(
            model_name='devteammember',
            new_name='dev_team_me_is_acti_d02dc7_idx',
            old_name='dev_team_me_is_acti_8b45e6_idx',
        ),
        migrations.RenameIndex(
            model_name='devteammember',
            new_name='dev_team_me_student_8479b4_idx',
            old_name='dev_team_me_student_77adfc_idx',
        ),
        migrations.RenameIndex(
            model_name='supportmessage',
            new_name='support_mes_thread__9d142c_idx',
            old_name='support_mes_thread__a073b8_idx',
        ),
        migrations.RenameIndex(
            model_name='supportmessage',
            new_name='support_mes_author__f290a6_idx',
            old_name='support_mes_author__b57e66_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='support_thr_status_d1d00c_idx',
            old_name='support_thr_status_3c0aea_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='support_thr_request_aa7495_idx',
            old_name='support_thr_request_d185ef_idx',
        ),
        migrations.RenameIndex(
            model_name='supportthread',
            new_name='support_thr_created_8d5faf_idx',
            old_name='support_thr_created_8dc699_idx',
        ),
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='user_settin_notify__fb7529_idx',
            old_name='user_settin_notify__0ba528_idx',
        ),
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='user_settin_notify__13cbb0_idx',
            old_name='user_settin_notify__29e11d_idx',
        ),
        migrations.RenameIndex(
            model_name='usersettings',
            new_name='user_settin_show_pr_3fe17c_idx',
            old_name='user_settin_show_pr_54fef8_idx',
        ),
    ]
