# Generated by Django 4.2.30 on 2026-05-03 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_userban_foreign_keys'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userban',
            name='user_bans_user_id_0ec7f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='userban',
            name='user_bans_banned__afb79c_idx',
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['user', 'is_active'], name='user_bans_user_id_0ec7f3_idx'),
        ),
        migrations.AddIndex(
            model_name='userban',
            index=models.Index(fields=['banned_by'], name='user_bans_banned__afb79c_idx'),
        ),
    ]
